language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - cd scraper && npm install && cd ..
script:
  - cd scraper && npm run scrape && npm run train && npm run test
