name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        cd scraper
        mkdir -p dist/json
        npm install
        cp ./node_modules/@tensorflow-models/knn-classifier/dist/knn-classifier.js ./node_modules/@tensorflow-models/knn-classifier/dist/index.js 
        node scrape.js
        node train.js
        node test.js
    - name: publish current model
      uses: actions/upload-artifact@master
      with:
        name: final_emotions_model
        path: scraper/dist/final_emotions_model.json
      env:
        CI: true
